<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018/8/15 0015
 * Time: 14:09
 */

return array(
    array("jobname"=>"农、林、牧、渔业","parentID"=>"1","level"=>1),
    array("jobname"=>"采矿业","parentID"=>"1","level"=>1),
    array("jobname"=>"制造业","parentID"=>"1","level"=>1),
    array("jobname"=>"住宿和餐饮业","parentID"=>"1","level"=>1),
    array("jobname"=>"金融业","parentID"=>"1","level"=>1),
    array("jobname"=>"房地产业","parentID"=>"1","level"=>1),
    array("jobname"=>"租赁和商务服务","parentID"=>"1","level"=>1),
    array("jobname"=>"电力、燃气及水的生产和供应","parentID"=>"1","level"=>1),
    array("jobname"=>"建筑业","parentID"=>"1","level"=>1),
    array("jobname"=>"科学研究、技术服务和地质勘查","parentID"=>"1","level"=>1),
    array("jobname"=>"水利、环境和公共设施管理","parentID"=>"1","level"=>1),
    array("jobname"=>"居民服务和其他服务","parentID"=>"1","level"=>1),
    array("jobname"=>"教育","parentID"=>"1","level"=>1),
    array("jobname"=>"交通运输、仓储和邮政","parentID"=>"1","level"=>1),
    array("jobname"=>"信息传输、计算机服务和软件业","parentID"=>"1","level"=>1),
    array("jobname"=>"批发和零售","parentID"=>"1","level"=>1),
    array("jobname"=>"卫生、社会保障和社会福利","parentID"=>"1","level"=>1),
    array("jobname"=>"公共管理和社会组织","parentID"=>"1","level"=>1),
    array("jobname"=>"国际组织","parentID"=>"1","level"=>1),
    array("jobname"=>"农业","parentID"=>"2","level"=>2),
    array("jobname"=>"林业","parentID"=>"2","level"=>2),
    array("jobname"=>"畜牧业","parentID"=>"2","level"=>2),
    array("jobname"=>"渔业","parentID"=>"2","level"=>2),
    array("jobname"=>"农、林、牧、渔服务","parentID"=>"3","level"=>2),
    array("jobname"=>"煤炭开采和洗选业","parentID"=>"3","level"=>2),
    array("jobname"=>"石油和天然气开采","parentID"=>"3","level"=>2),
    array("jobname"=>"黑色金属矿采选","parentID"=>"3","level"=>2),
    array("jobname"=>"有色金属矿采选","parentID"=>"3","level"=>2),
    array("jobname"=>"非金属矿采选","parentID"=>"3","level"=>2),
    array("jobname"=>"其他采矿业","parentID"=>"3","level"=>2),
    array("jobname"=>"农副食品加工业","parentID"=>"4","level"=>2),
    array("jobname"=>"谷物磨制","parentID"=>"4","level"=>2),
    array("jobname"=>"饲料","parentID"=>"4","level"=>2),
    array("jobname"=>"植物油","parentID"=>"4","level"=>2),
    array("jobname"=>"制糖","parentID"=>"4","level"=>2),
    array("jobname"=>"屠宰及肉类","parentID"=>"4","level"=>2),
    array("jobname"=>"水产品","parentID"=>"4","level"=>2),
    array("jobname"=>"蔬菜、水果和坚果","parentID"=>"4","level"=>2),
    array("jobname"=>"其它农副食品","parentID"=>"4","level"=>2),
    array("jobname"=>"焙烧食品制造","parentID"=>"4","level"=>2),
    array("jobname"=>"糕点、面包","parentID"=>"4","level"=>2),
    array("jobname"=>"饼干及其他焙烤食品","parentID"=>"4","level"=>2),
    array("jobname"=>"糖果、巧克力及蜜饯","parentID"=>"4","level"=>2),
    array("jobname"=>"方便食品","parentID"=>"4","level"=>2),
    array("jobname"=>"液体乳及乳制品","parentID"=>"4","level"=>2),
    array("jobname"=>"罐头","parentID"=>"4","level"=>2),
    array("jobname"=>"调味品、发酵制品","parentID"=>"4","level"=>2),
    array("jobname"=>"其他食品","parentID"=>"4","level"=>2),
    array("jobname"=>"饮料制造","parentID"=>"4","level"=>2),
    array("jobname"=>"烟草制品","parentID"=>"4","level"=>2),
    array("jobname"=>"纺织业","parentID"=>"4","level"=>2),
    array("jobname"=>"纺织服装、鞋、帽制造","parentID"=>"4","level"=>2),
    array("jobname"=>"皮革、毛皮、羽毛（绒）及其制品","parentID"=>"4","level"=>2),
    array("jobname"=>"木材加工及木、竹、藤、棕、草制品","parentID"=>"4","level"=>2),
    array("jobname"=>"家具制品","parentID"=>"4","level"=>2),
    array("jobname"=>"造纸及纸制品","parentID"=>"4","level"=>2),
    array("jobname"=>"印刷业和记录媒介的复制","parentID"=>"4","level"=>2),
    array("jobname"=>"文教体育用品制造","parentID"=>"4","level"=>2),
    array("jobname"=>"石油加工、炼焦及核燃料加工","parentID"=>"4","level"=>2),
    array("jobname"=>"化学原料及化学制品","parentID"=>"4","level"=>2),
    array("jobname"=>"其他化学原料","parentID"=>"4","level"=>2),
    array("jobname"=>"肥料","parentID"=>"4","level"=>2),
    array("jobname"=>"农药","parentID"=>"4","level"=>2),
    array("jobname"=>"涂料、油墨、颜料及类似产品","parentID"=>"4","level"=>2),
    array("jobname"=>"合成材料","parentID"=>"4","level"=>2),
    array("jobname"=>"专用化学产品","parentID"=>"4","level"=>2),
    array("jobname"=>"日用化学产品","parentID"=>"4","level"=>2),
    array("jobname"=>"医药制造","parentID"=>"4","level"=>2),
    array("jobname"=>"化学纤维制造","parentID"=>"4","level"=>2),
    array("jobname"=>"橡胶制品","parentID"=>"4","level"=>2),
    array("jobname"=>"塑料制品","parentID"=>"4","level"=>2),
    array("jobname"=>"非金属物制品","parentID"=>"4","level"=>2),
    array("jobname"=>"水泥、石灰和石膏的制造","parentID"=>"4","level"=>2),
    array("jobname"=>"水泥及石膏制品制造","parentID"=>"4","level"=>2),
    array("jobname"=>"砖瓦、石材及其他建筑材料","parentID"=>"4","level"=>2),
    array("jobname"=>"玻璃及玻璃制品","parentID"=>"4","level"=>2),
    array("jobname"=>"陶瓷制品","parentID"=>"4","level"=>2),
    array("jobname"=>"耐火材料制品","parentID"=>"4","level"=>2),
    array("jobname"=>"黑色金属冶炼及压延加工","parentID"=>"4","level"=>2),
    array("jobname"=>"有色金属冶炼及压延加工","parentID"=>"4","level"=>2),
    array("jobname"=>"金属制品","parentID"=>"4","level"=>2),
    array("jobname"=>"通用设备制造","parentID"=>"4","level"=>2),
    array("jobname"=>"专用设备制造","parentID"=>"4","level"=>2),
    array("jobname"=>"交通运输设备制造","parentID"=>"4","level"=>2),
    array("jobname"=>"电气机械及器材制造","parentID"=>"4","level"=>2),
    array("jobname"=>"通信设备、计算机及其他电子设备","parentID"=>"4","level"=>2),
    array("jobname"=>"仪器仪表及文化、办公用机械","parentID"=>"4","level"=>2),
    array("jobname"=>"工艺品及其他","parentID"=>"4","level"=>2),
    array("jobname"=>"废弃资源和废旧材料回收加工","parentID"=>"4","level"=>2),
    array("jobname"=>"电力、热力的生产和供应","parentID"=>"5","level"=>2),
    array("jobname"=>"燃气生产和供应","parentID"=>"5","level"=>2),
    array("jobname"=>"水的生产和供应","parentID"=>"5","level"=>2),
    array("jobname"=>"房屋和土木工程建筑","parentID"=>"6","level"=>2),
    array("jobname"=>"建筑安装","parentID"=>"6","level"=>2),
    array("jobname"=>"其他建筑","parentID"=>"6","level"=>2),




    array("jobname"=>"铁路运输","parentID"=>"7","level"=>2),
    array("jobname"=>"道路运输","parentID"=>"7","level"=>2),
    array("jobname"=>"城市公共交通","parentID"=>"7","level"=>2),
    array("jobname"=>"水上运输","parentID"=>"7","level"=>2),
    array("jobname"=>"航空运输","parentID"=>"7","level"=>2),
    array("jobname"=>"管道运输","parentID"=>"7","level"=>2),
    array("jobname"=>"装卸搬运和其他运输","parentID"=>"7","level"=>2),
    array("jobname"=>"装卸搬运","parentID"=>"7","level"=>2),
    array("jobname"=>"运输代理服务","parentID"=>"7","level"=>2),
    array("jobname"=>"仓储业","parentID"=>"7","level"=>2),
    array("jobname"=>"邮政业","parentID"=>"7","level"=>2),
    array("jobname"=>"电信和其他信息传输服务","parentID"=>"8","level"=>2),
    array("jobname"=>"电信","parentID"=>"8","level"=>2),
    array("jobname"=>"互联网信息","parentID"=>"8","level"=>2),
    array("jobname"=>"广播电视传输","parentID"=>"8","level"=>2),
    array("jobname"=>"卫星传输","parentID"=>"8","level"=>2),
    array("jobname"=>"计算机服务","parentID"=>"8","level"=>2),
    array("jobname"=>"计算机系统","parentID"=>"8","level"=>2),
    array("jobname"=>"数据处理","parentID"=>"8","level"=>2),
    array("jobname"=>"计算机维修","parentID"=>"8","level"=>2),
    array("jobname"=>"其他计算机","parentID"=>"8","level"=>2),
    array("jobname"=>"软件业","parentID"=>"8","level"=>2),
    array("jobname"=>"批发","parentID"=>"9","level"=>2),
    array("jobname"=>"农畜产品","parentID"=>"9","level"=>2),
    array("jobname"=>"食品、饮料和烟草制品","parentID"=>"9","level"=>2),
    array("jobname"=>"纺织、服装及日用品","parentID"=>"9","level"=>2),
    array("jobname"=>"文化、体育用品及器材","parentID"=>"9","level"=>2),
    array("jobname"=>"医药及医疗器材","parentID"=>"9","level"=>2),
    array("jobname"=>"矿产品、建材、化工产品","parentID"=>"9","level"=>2),
    array("jobname"=>"机械设备、五金交电及电子产品","parentID"=>"9","level"=>2),
    array("jobname"=>"贸易经纪与代理","parentID"=>"9","level"=>2),
    array("jobname"=>"其他批发","parentID"=>"9","level"=>2),
    array("jobname"=>"零售业","parentID"=>"9","level"=>2),
    array("jobname"=>"综合零售","parentID"=>"9","level"=>2),
    array("jobname"=>"百货","parentID"=>"9","level"=>2),
    array("jobname"=>"超级市场","parentID"=>"9","level"=>2),
    array("jobname"=>"其他综合","parentID"=>"9","level"=>2),
    array("jobname"=>"食品、饮料及烟草制品","parentID"=>"9","level"=>2),
    array("jobname"=>"纺织、服装及日用品","parentID"=>"9","level"=>2),
    array("jobname"=>"文化、体育用品及器材","parentID"=>"9","level"=>2),
    array("jobname"=>"医药及医疗器材","parentID"=>"9","level"=>2),
    array("jobname"=>"汽车、摩托车、燃料及零配件","parentID"=>"9","level"=>2),
    array("jobname"=>"家用电器及电子产品","parentID"=>"9","level"=>2),
    array("jobname"=>"五金、家具及室内装修材料","parentID"=>"9","level"=>2),
    array("jobname"=>"住宿","parentID"=>"10","level"=>2),
    array("jobname"=>"旅游饭店","parentID"=>"10","level"=>2),
    array("jobname"=>"一般旅馆","parentID"=>"10","level"=>2),
    array("jobname"=>"其他住宿","parentID"=>"10","level"=>2),
    array("jobname"=>"餐饮","parentID"=>"10","level"=>2),
    array("jobname"=>"银行业","parentID"=>"11","level"=>2),
    array("jobname"=>"证券","parentID"=>"11","level"=>2),
    array("jobname"=>"保险","parentID"=>"11","level"=>2),
    array("jobname"=>"其他金融活动","parentID"=>"11","level"=>2),
    array("jobname"=>"金融信托和管理","parentID"=>"11","level"=>2),
    array("jobname"=>"金融租赁","parentID"=>"11","level"=>2),
    array("jobname"=>"财务公司","parentID"=>"11","level"=>2),
    array("jobname"=>"邮政储蓄","parentID"=>"11","level"=>2),
    array("jobname"=>"典当","parentID"=>"11","level"=>2),
    array("jobname"=>"其他","parentID"=>"11","level"=>2),
    array("jobname"=>"房地产开发经营","parentID"=>"12","level"=>2),
    array("jobname"=>"物业管理","parentID"=>"12","level"=>2),
    array("jobname"=>"房地产中介服务","parentID"=>"12","level"=>2),
    array("jobname"=>"其他","parentID"=>"12","level"=>2),
    array("jobname"=>"租赁","parentID"=>"13","level"=>2),
    array("jobname"=>"机械设备租赁","parentID"=>"13","level"=>2),
    array("jobname"=>"汽车","parentID"=>"13","level"=>2),
    array("jobname"=>"农业机械","parentID"=>"13","level"=>2),
    array("jobname"=>"建筑工程机械与设备","parentID"=>"13","level"=>2),
    array("jobname"=>"计算机及通讯","parentID"=>"13","level"=>2),
    array("jobname"=>"其他","parentID"=>"13","level"=>2),
    array("jobname"=>"商务服务","parentID"=>"13","level"=>2),
    array("jobname"=>"企业管理服务","parentID"=>"13","level"=>2),
    array("jobname"=>"法律服务","parentID"=>"13","level"=>2),
    array("jobname"=>"咨询与调查","parentID"=>"13","level"=>2),
    array("jobname"=>"广告业","parentID"=>"13","level"=>2),
    array("jobname"=>"知识产权","parentID"=>"13","level"=>2),
    array("jobname"=>"职业中介","parentID"=>"13","level"=>2),
    array("jobname"=>"市场管理","parentID"=>"13","level"=>2),
    array("jobname"=>"旅行社","parentID"=>"13","level"=>2),
    array("jobname"=>"其他商务","parentID"=>"13","level"=>2),
    array("jobname"=>"会议及展览","parentID"=>"13","level"=>2),
    array("jobname"=>"包装","parentID"=>"13","level"=>2),
    array("jobname"=>"保安","parentID"=>"13","level"=>2),
    array("jobname"=>"办公服务","parentID"=>"13","level"=>2),
    array("jobname"=>"研究与试验发展","parentID"=>"14","level"=>2),
    array("jobname"=>"专业技术服务","parentID"=>"14","level"=>2),
    array("jobname"=>"气象服务","parentID"=>"14","level"=>2),
    array("jobname"=>"地震服务","parentID"=>"14","level"=>2),
    array("jobname"=>"海洋服务","parentID"=>"14","level"=>2),
    array("jobname"=>"测绘服务","parentID"=>"14","level"=>2),
    array("jobname"=>"技术检测","parentID"=>"14","level"=>2),
    array("jobname"=>"环境监测","parentID"=>"14","level"=>2),
    array("jobname"=>"工程技术与规划管理","parentID"=>"14","level"=>2),
    array("jobname"=>"科技交流和推广服务","parentID"=>"14","level"=>2),
    array("jobname"=>"地质勘查","parentID"=>"14","level"=>2),



    array("jobname"=>"水利管理","parentID"=>"15","level"=>2),
    array("jobname"=>"环境管理","parentID"=>"15","level"=>2),
    array("jobname"=>"自然保护","parentID"=>"15","level"=>2),
    array("jobname"=>"环境治理","parentID"=>"15","level"=>2),
    array("jobname"=>"公共设施管理","parentID"=>"15","level"=>2),
    array("jobname"=>"居民服务","parentID"=>"16","level"=>2),
    array("jobname"=>"修理与维护","parentID"=>"16","level"=>2),
    array("jobname"=>"其他服务","parentID"=>"16","level"=>2),
    array("jobname"=>"清洁服务","parentID"=>"16","level"=>2),
    array("jobname"=>"学前","parentID"=>"17","level"=>2),
    array("jobname"=>"初等","parentID"=>"17","level"=>2),
    array("jobname"=>"中等","parentID"=>"17","level"=>2),
    array("jobname"=>"高等","parentID"=>"17","level"=>2),
    array("jobname"=>"卫生","parentID"=>"18","level"=>2),
    array("jobname"=>"社会保障","parentID"=>"18","level"=>2),
    array("jobname"=>"社会福利","parentID"=>"18","level"=>2),
    array("jobname"=>"新闻出版业","parentID"=>"19","level"=>2),
    array("jobname"=>"新闻业","parentID"=>"19","level"=>2),
    array("jobname"=>"出版","parentID"=>"19","level"=>2),
    array("jobname"=>"广播、电视、电影和音像","parentID"=>"19","level"=>2),
    array("jobname"=>"文化艺术","parentID"=>"19","level"=>2),
    array("jobname"=>"文艺创作与表演","parentID"=>"19","level"=>2),
    array("jobname"=>"艺术表演场馆","parentID"=>"19","level"=>2),
    array("jobname"=>"图书馆与档案馆","parentID"=>"19","level"=>2),
    array("jobname"=>"文物及文化保护","parentID"=>"19","level"=>2),
    array("jobname"=>"博物馆","parentID"=>"19","level"=>2),
    array("jobname"=>"其他","parentID"=>"19","level"=>2),
    array("jobname"=>"娱乐","parentID"=>"19","level"=>2),
    array("jobname"=>"体育","parentID"=>"19","level"=>2),






);




















